from pathlib import Path
import argparse,ast

def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--input',required=True); ap.add_argument('--output',required=True); a=ap.parse_args(); p=Path(a.input); tree=ast.parse(p.read_text()); funcs=[n for n in tree.body if isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef)) and not n.name.startswith('_')]; mod=p.stem; lines=['"""Generated test skeletons. Review expected values before enabling."""',f'import {mod}','','# Generated by Open Workflow Skills v2.0.0']
 for f in funcs:
  args=[x.arg for x in f.args.args]; lines += ['',f'def test_{f.name}_basic():',f'    # Signature: {f.name}({", ".join(args)})','    raise NotImplementedError("Define representative inputs and expected output")']
 out=Path(a.output); out.parent.mkdir(parents=True,exist_ok=True); out.write_text('\n'.join(lines)+'\n'); print(f'generated={len(funcs)} {out}')
if __name__=='__main__':main()
